### ISSUE TITLE
Add installation instructions into an md file "installation" and link it from the Readme

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#1]
Please add installation instruction into an md file "installation" and link it from the Readme.

If you copy any information from other pages, please ensure it is freely licensed and name relevant main authors in the commit message.

**Comment by ms10398** [comment]
On it @mariobehling

**Comment by ms10398** [comment]
@mariobehling Can we use this link as reference and use the content from it  https://help.ubuntu.com/community/Lubuntu/InstallingLubuntu
