### ISSUE TITLE
Add icons for social media 

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#11]
Add icons for social media similar fossasia.org at the end of the link section and above the Licence.

![screenshot from 2017-12-21 09-54-33](https://user-images.githubusercontent.com/1583873/34248118-20e24fe4-e635-11e7-8175-0dc3c408daee.png)

Facebook https://www.facebook.com/lubuntudesktop/
Twitter https://twitter.com/lubuntudesktop/
GitHub https://github.com/lubuntu-dev/
YouTube https://www.youtube.com/channel/UC0nEnI4yt2OCiZwRT0q90tQ/
Launchpad https://launchpad.net/~lubuntu-x
Google+ https://plus.google.com/u/0/107909502516592034334/
Linkedin https://www.linkedin.com/groups/3742725

**Comment by alirizwi** [comment]
claiming this
