### ISSUE TITLE
Change list of requirements of Windows and lubuntu into table

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#13]
There is a list of requirements in the docs https://github.com/lubuntu-dev/docs.lubuntu.net/blob/master/lubuntu_vs_Windows.md#lubuntu-hardware-requirements-vs-windows-hardware-requirements.

Please change this list into a table with four headings:
Requirements, Windows, Lubuntu Minimal, Lubuntu Recommended

**Comment by alirizwi** [comment]
claiming this

**Comment by mariobehling** [comment]
Please only claim and finish one item at a time. We try to avoid mass claiming and issues that don't get solved in the end sometimes.

**Comment by ms10398** [comment]
Claiming will make a relevant PR soon
