### ISSUE TITLE
Add an Installed Tools md file with information and link to it from the Readme.md

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#2]
If you copy any information from other pages, please ensure it is freely licensed and name relevant main authors in the commit message.

**Comment by mariobehling** [comment]
The issue is not entirely closed, as there should ideally be links to the websites of the components. Please add those. Thank you.

**Comment by ParthS007** [comment]
closing this as it is completed by @ms10398  in #22
