### ISSUE TITLE
Provide separate table for Hardware Requirements vs Windows Hardware Requirements until v14.10 and one for lubuntu versions above

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#20]
Please provide a separate table for "Hardware Requirements vs Windows Hardware Requirements" until v14.10 and one for lubuntu versions above on the page https://github.com/lubuntu-dev/docs.lubuntu.net/blob/master/lubuntu_vs_Windows.md

Currently the requirements are not specific enough.

**Comment by gabru-md** [comment]
@mariobehling I would like to work on this issue and provide with a relevant PR soon 
:+1:

**Comment by ms10398** [comment]
I think its updated by Mario already.
Still check it once

**Comment by gabru-md** [comment]
Oh yes! i saw it just now, 
Well @mariobehling I guess that this issue can now be closed.
