### ISSUE TITLE
markdown format visible

### ISSUE THREAD

**Issue by sayak119** [lubuntu-dev/docs.lubuntu.net#23]
in https://docs.lubuntu.net/lubuntu_vs_Ubuntu.html the raw markdown format is visible as shown in the screenshots 

![screenshot from 2017-12-22 22-18-25](https://user-images.githubusercontent.com/28414920/34305855-2b279ffe-e766-11e7-970b-096e166f0f4a.png)

![screenshot from 2017-12-22 22-18-31](https://user-images.githubusercontent.com/28414920/34305903-6d3995fa-e766-11e7-80df-516d1cf1c9e4.png)

I want to work on this

**Comment by mariobehling** [comment]
Fixed. Thanks.
