### ISSUE TITLE
Fix release info and check all areas of 16.04 

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#40]
The release notes of 16.04 are still not working as expected. Please check and open and issue and help to fix it: https://docs.lubuntu.net/releases/lubuntu1604_release_notes.html

Also check that the download page is working as expected.

**Comment by ms10398** [comment]
Claiming it

**Comment by ms10398** [comment]
I found out the release notes were of ubuntu instead of lubuntu so i have chnaged it in my PR.

**Comment by mariobehling** [comment]
* There are still shortened pad.lv links which should be to the final location
* The list of full applications should direct to the list of applications on this page

**Comment by ms10398** [comment]
Yes checking and doing it
