### ISSUE TITLE
Find 11.10 release for download

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#48]
The 11.10 release is no longer hosted on the Ubuntu download site. Please find an alternative site where it can be downloaded and add the links.

**Comment by anshumanv** [comment]
Will a Gdrive link be good enough @mariobehling? :smile:

**Comment by anshumanv** [comment]
I got this link to download i386 ISO - [link](https://archive.org/download/Lubuntu11.10DesktopI386Iso/lubuntu-11.10-desktop-i386.iso) from archive.org

Is this worth adding?

**Comment by mariobehling** [comment]
Yes, very good. Thanks.

**Comment by anshumanv** [comment]
Awesome. :rocket: 
Sending a PR soon.

**Comment by anshumanv** [comment]
Sadly I'm not able to find AMD64 Desktop ISO, nor alternate images.
Sending a PR with what I got and will iterate as I get them.

**Comment by ParthS007** [comment]
sure @anshumanv , go ahead 👍
