### ISSUE TITLE
Create a page lubuntu on older computers

### ISSUE THREAD

**Issue by mariobehling** [lubuntu-dev/docs.lubuntu.net#7]
Add a file "lubuntu_on_older_computers.md" into the root directory and add information how to install it on older PCs following ideas of this page: https://wiki.ubuntu.com/Lubuntu/AdvancedMethods

Ensure you name contributors of information in the commit message should you copy any information.

**Comment by yashLadha** [comment]
@mariobehling Will it be a jekyll page or a wiki?
